# Используем базовый образ Liquibase
FROM liquibase/liquibase

# Копируем ваши файлы в контейнер
# Например, копируем changelog.xml и другие файлы в директорию /liquibase/changelog
COPY ./changelog /liquibase/changelog
